### ISSUE TITLE
Support for coursier

### ISSUE THREAD

**Issue by Jentsch** [danielnixon/playwarts#24]
Currently the file path of ivy is hard coded in [PlayWarts.scala](https://github.com/danielnixon/playwarts/blob/master/sbt-plugin/src/main/scala/org/danielnixon/playwarts/PlayWarts.scala#L23). Unfortunately coursier places the dependencies somewhere else. I submitted a PR for puffnfresh/wartremover#246 which would make `wartremoverClasspaths` as task key. As soon as this is published, the hard coded pathes could be replaced by something like:

``` scala
wartremoverClasspaths ++= {
  val artifacts = update.value.configuration("compile")
    .map(_.modules.flatMap(_.artifacts))
    .getOrElse(Nil)

    artifacts.collect {
      case (artifact, file) if artifact.name == "playwarts_2.11" =>
        file.absolutePath
    }
}
```

**Comment by danielnixon** [comment]
Looks good, thanks. PR welcome. :)

**Comment by Jentsch** [comment]
Thanks!
