### ISSUE TITLE
Unresolvable dependency in 2.12 / 1.1.0 release

### ISSUE THREAD

**Issue by elkozmon** [danielnixon/playwarts#30]
Hi, I am using playwarts version 1.1.0 for scala 2.12, sbt 1.0.2. 

```
addSbtPlugin("org.danielnixon" % "sbt-playwarts" % "1.1.0")
```

When I try to build my project, it fails with this:
```
[error] (core/*:update) sbt.librarymanagement.ResolveException: unresolved dependency: org.danielnixon#playwarts_2.12;1.1.0-SNAPSHOT: not found
```

Then I looked for playwarts jar in my .ivy2 cache:
```
-rw-r--r-- 1 elkozmon users 12215 Oct  7 03:04 /home/elkozmon/.ivy2/cache/scala_2.12/sbt_1.0/org.danielnixon/sbt-playwarts/jars/sbt-playwarts-1.1.0.jar
```

I noticed that you use version for auto import provided by build info sbt plugin, so I decompiled `BuildInfo.class` in that jar using jad, and found this inside:
```
private final String version = "1.1.0-SNAPSHOT";
private final String organization = "org.danielnixon";
private final String artifactID = "playwarts";
```

I guess that snapshot version must have accidentally slipped through there.

**Comment by danielnixon** [comment]
Looks like I'm hitting a limitation in sbt-release. Please try playwarts version `1.1.2`.

**Comment by elkozmon** [comment]
Ok so I switched to `1.1.2` and it's working fine :) thanks
